name: if example
on:
  push:
    branches:
      - main
      - develop
      - feature/**
jobs:
  quality-checks:
      if: startsWith(github.ref_name, 'feature') && github.event_name == 'push'
      runs-on: ubuntu-latest
      steps:
<<<<<<< HEAD
        - name: perform code quality checks
          run: echo "Performing code quality checks for feature branch"
=======
        -name: perform code quality checks
         run: echo "Performing code quality checks for feature branch"
  
>>>>>>> bc9b2b357ff9590e1c5cee098f714f15bfb3d7ca
  dev-deploy:
      if: github.ref_name == 'develop' && gihub.event_name == 'push'
      runs-on: ubuntu-latest
      steps:
<<<<<<< HEAD
        - name: deploy to development environment
          run: echo "Deployed to development environment"
=======
        -name: deploy to development environment
         run: echo "Deployed to development environment"
>>>>>>> bc9b2b357ff9590e1c5cee098f714f15bfb3d7ca
  prod-deploy:
      if: github.ref_name == 'main' && github.event_name == 'push'
      runs-on: ubuntu-latest
      steps:
<<<<<<< HEAD
        - name: deploy to production environment
          run: echo "Deployed to production environment"
=======
        -name: deploy to production environment
         run: echo "Deployed to production environment"
>>>>>>> bc9b2b357ff9590e1c5cee098f714f15bfb3d7ca
  success-notification:
      if: success() && !failure()
      runs-on: ubuntu-latest
      steps:
<<<<<<< HEAD
        - name: send success notification
          run: echo "Sending Success notfication to team"
=======
        -name: send success notification
         run: echo "Sending Success notfication to team"
>>>>>>> bc9b2b357ff9590e1c5cee098f714f15bfb3d7ca
  failure-notification:
      if: failure()
      runs-on: ubuntu-latest
      steps:
<<<<<<< HEAD
        - name: send failure notification
          run: echo "Sending Failure notification to team"
=======
        -name: send failure notification
         run: echo "Sending Failure notification to team"
>>>>>>> bc9b2b357ff9590e1c5cee098f714f15bfb3d7ca
       