name: Input demo
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Please provide the environment name to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod
          - staging
      artifact_tag:
        description: Provide the artifact tag
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: depoloy the app
        run: echo "Deploying the ${{ inputs.artifact_tag }} to ${{ inputs.environment }}"