name: Static website hosting
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{  secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: code to static website
        run: |
          aws s3 sync ./ s3://hosting-static-website-from-github-action/ \
          --exclude "*" \
          --include "index.html"
        
      
